version: "3"
services:
  mysqldb:
    image: mysql:8
    container_name: "mysql-srv"
    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_USER: quenede
      MYSQL_PASSWORD: "@Quenede1393"
      MYSQL_ROOT_PASSWORD: "@Quenede1393"
    restart: always
    networks:
      - my-network

  appnode:
    build:
      dockerfile: ./.docker/nodejs/node
    container_name: "nodejs"
    #network_mode: host
    networks:
      - my-network
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    restart: always
    depends_on:
      - mysqldb
volumes:
  mysqldb:
networks:
  my-network:
